import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";

const NotoSansBangali = Noto_Sans_Bengali({
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${NotoSansBangali} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
         <Navbar/>
        
        {children}
        </body>
    </html>
  );
}
